CREATE TABLE Users (
	userId INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  userType ENUM('STUDENT', 'INSTRUCTOR', 'ADMIN') NOT NULL,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  userName VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE Categories (
  categoryId INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  categoryName VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE Courses (
	courseId INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  courseName VARCHAR(255) NOT NULL,
  courseDescription MEDIUMTEXT,
	isLive BOOLEAN NOT NULL,
	dateWentLive DATE,
	categoryFk INT NULL,
	CONSTRAINT FOREIGN KEY(`categoryFk`) REFERENCES `Categories`(`categoryId`)
) ENGINE=InnoDB;

CREATE TABLE UsersCourses (
	userCourseId INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  userFk INT NOT NULL,
  courseFk INT NOT NULL,
  CONSTRAINT FOREIGN KEY(`userFk`) REFERENCES `Users`(`userId`),
  CONSTRAINT FOREIGN KEY(`courseFk`) REFERENCES `Courses`(`courseId`)
) ENGINE=InnoDB;

CREATE TABLE CourseModules (
  courseModuleId INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  courseFk INT NOT NULL,
  courseModuleHTML MEDIUMTEXT NULL,
  courseModuleOrder INT NOT NULL,
  CONSTRAINT FOREIGN KEY(`courseFk`) REFERENCES `Courses`(`courseId`)
) ENGINE=InnoDB;

CREATE TABLE Languages (
  languageId INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  languageName VARCHAR(255) NOT NULL,
	languageCountry VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE LanguagesCourses (
	languageCourseId INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  languageFk INT NOT NULL,
  courseFk INT NOT NULL,
  CONSTRAINT FOREIGN KEY(`languageFk`) REFERENCES `Users`(`userId`),
  CONSTRAINT FOREIGN KEY(`courseFk`) REFERENCES `Courses`(`courseId`)
) ENGINE=InnoDB;
